#!/bin/bash

# Copy HTML files to parent directory if they are newer or do not exist
for file in *.html
do
  if [ ! -e "../$file" ] || [ "$file" -nt "../$file" ]
  then
    cp "$file" "../$file"
    echo "Copied $file to parent directory"
  fi
done
